// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgl5VDEduHP88KHCS4EQoasmMZsUBe7s',
    appId: '1:265193445997:web:71a76ca004b71156597d64',
    messagingSenderId: '265193445997',
    projectId: 'healthcare-awareness',
    authDomain: 'healthcare-awareness.firebaseapp.com',
    storageBucket: 'healthcare-awareness.firebasestorage.app',
    measurementId: 'G-MS932QVDX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSdK09SO6LJAexaiSG10Ued50U7E6FRRY',
    appId: '1:265193445997:android:28db4f2699de8354597d64',
    messagingSenderId: '265193445997',
    projectId: 'healthcare-awareness',
    storageBucket: 'healthcare-awareness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB19ht-5uHFY0Z5eIALEqCHCHTz7uOK1M',
    appId: '1:265193445997:ios:d1df443bcc766302597d64',
    messagingSenderId: '265193445997',
    projectId: 'healthcare-awareness',
    storageBucket: 'healthcare-awareness.firebasestorage.app',
    iosBundleId: 'com.example.gramcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB19ht-5uHFY0Z5eIALEqCHCHTz7uOK1M',
    appId: '1:265193445997:ios:d1df443bcc766302597d64',
    messagingSenderId: '265193445997',
    projectId: 'healthcare-awareness',
    storageBucket: 'healthcare-awareness.firebasestorage.app',
    iosBundleId: 'com.example.gramcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgl5VDEduHP88KHCS4EQoasmMZsUBe7s',
    appId: '1:265193445997:web:80c71df4cf6f6bd5597d64',
    messagingSenderId: '265193445997',
    projectId: 'healthcare-awareness',
    authDomain: 'healthcare-awareness.firebaseapp.com',
    storageBucket: 'healthcare-awareness.firebasestorage.app',
    measurementId: 'G-CNZZ12WGX4',
  );
}
